config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :subcategories
  resources :categories
  resources :products
  devise_for :users
  get "about" => "pages#about"
  get "pinview" => "products#pinview"
  root "products#index"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  has_many :subcategories
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  belongs_to :subcatogory
  
  has_attached_file :image, :styles => { :large => "600x600", :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

  has_attached_file :document
  validates_attachment :document, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }

  include FriendlyId
    friendly_id :product, :use => [:slugged, :simple_i18n]
  end

end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  belongs_to :category
  has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  respond_to :html

  def index
    @categories = Category.all
    respond_with(@categories)
  end

  def show
    respond_with(@category)
  end

  def new
    @category = Category.new
    respond_with(@category)
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.save
    respond_with(@category)
  end

  def update
    @category.update(category_params)
    respond_with(@category)
  end

  def destroy
    @category.destroy
    respond_with(@category)
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy ]
  before_action :authenticate_user!, except: [:index, :show, :pinview]

  def index
    @products = Product.all.order("category_id", "pname").paginate(:page => params[:page], :per_page => 16)
  end
  
  def pinview
    @products = Product.all.order("category_id", "pname").paginate(:page => params[:page], :per_page => 30)
  end

  def show
  end

  def new
    @product = current_user.products.build
  end

  def edit
  end

  def create
    @product = current_user.products.build(product_params)
    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
     @product = Product.find(params[:id])
    end

    def correct_user
      @product = current_user.products.find_by(id: params[:id])
      redirect_to products_path, notice: "Not authorized to edit this product" if @product.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:description, :category, :subcategory, :image, :document, :pname, :label, :grade, :pack_size)
    end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :set_subcategory, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]


  respond_to :html

  def index
    @subcategories = Subcategory.all.order("category_id", "description")
    respond_with(@subcategories)
  end

  def show
    respond_with(@subcategory)
  end

  def new
    @subcategory = Subcategory.new
    respond_with(@subcategory)
  end

  def edit
  end

  def create
    @subcategory = Subcategory.new(subcategory_params)
    @subcategory.save
    respond_with(@subcategory)
  end

  def update
    @subcategory.update(subcategory_params)
    respond_with(@subcategory)
  end

  def destroy
    @subcategory.destroy
    respond_with(@subcategory)
  end

  private
    def set_subcategory
      @subcategory = Subcategory.find(params[:id])
    end

    def subcategory_params
      params.require(:subcategory).permit(:description, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h3>Categories</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.description %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Category List', categories_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">CH Belt</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
	<ul class="nav navbar-nav navbar-right">
	        <li><%= link_to "Home", root_path %></li>
			<li><%= link_to "PinView", pinview_path %></li>
	        <li><%= link_to "About", about_path %></li>
	        <% if user_signed_in? %>
				<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin <span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu">
						          <li>
						            <%= link_to new_product_path do %>
						            <span class="glyphicon glyphicon-plus"></span> New Product
						            <% end %>
						          </li>
				<li class="divider"></li>
				<li><%= link_to 'Category List', categories_path %></li>
				<li><%= link_to 'Sub-Category List', subcategories_path %></li>	
				<li class="divider"></li>
				<li><%= link_to "Account Settings", edit_user_registration_path %></li>
				</ul>
				</li>
			<li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
	        <% else %>
	          <li><%= link_to "Sign in", new_user_session_path %></li>
	        <% end %>
	 </ul>
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container --> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chbelt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
		<%= render 'layouts/header' %>
     <div class="container">
 		<% flash.each do |name, msg| %>
 		     <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
 		<% end %>
          <%= yield %>
     </div>

</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
     <h2>Welcome to my app!</h2>
     <% if user_signed_in? %>
          # do something
     <% else %>
       <p>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
       </p>
  <% end %>  
</div>

app/views/pages/about.html.erb
<div class="jumbotron">
	<h2>About this site!</h2>
	<p>Just a cool product list.</p>
</div>

app/views/products/_form.html.erb
<%= form_for @product, html: { multipart: true } do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label "Product Name" %>
    <%= f.text_field :pname, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :label %> 
	<%= f.text_field :label, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :grade %> 
	<%= f.text_field :grade, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :pack_size %> 
	<%= f.text_field :pack_size, class: "form-control" %>
  </div>
  <div class="form-group">
  <%= f.label "Category" %>
  <% options = options_from_collection_for_select(Category.all, 'id', 'description') %>
  <%= f.select :category_id, options, :input_html => { class: "form-control" } %>
  </div>
  <div class="form-group">
  <%= f.label "Sub-Category" %>
  <% options = options_from_collection_for_select(Subcategory.all.order("category_id", "description"), 'id', 'description') %>
  <%= f.select :subcategory_id, options, :input_html => { class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :document %>
    <%= f.file_field :document, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h3>Products</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Product</th>
      <th>Label</th>
      <th>Grade</th>
	  <th>Pack Size</th>
	  <th>Spec Sheet</th>
	  <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.pname %></td>
		<td><%= product.label %></td>
		<td><%= product.grade %></td>
		<td><%= product.pack_size %></td>
		<td>
			<% if product.document.file? %>
			  <%= link_to 'Spec Sheet (PDF)', product.document.url, :target => "_blank" %>
			<% end %>
		</td>
		<td><%= link_to 'Show', product_path(product) %></td>
		<% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="center">
   <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/products/new.html.erb
<h2>Add product</h2>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/pinview.html.erb
<div id="products" class="transitions-enabled">
  <% @products.each do |product| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(product.image.url(:medium)), product %>
      <div class="panel-body">
		<h3><%= product.pname %></h3>  
        <% if product.description? %>
		<%= product.description %><br>
		<% end %>
		<b>Label: &nbsp</b><%= product.label %><br>
		<b>Grade: &nbsp</b><%= product.grade %><br>
		<b>Pack Size: &nbsp</b><%= product.pack_size %><br>
			<% if product.document.file? %>
			  <%= link_to 'Spec Sheet (PDF)', product.document.url, :target => "_blank" %><br>
			<% end %>
			<%= link_to 'Show', product_path(product) %>
        <% if user_signed_in? %>
            <%= link_to edit_product_path(product) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
            <%= link_to product, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
			<% end %>
		</p>
      </div>
    </div>
  <% end %>
</div>
<div class="center">
   <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<%= image_tag @product.image.url (:medium) %>
	<h3><%= @product.pname %></h3>
  	<p>
	  <%= @product.description %><br>
	  <b>Label: &nbsp<%= @product.label %><br>
	  <b>Grade: &nbsp<%= @product.grade %><br>
	  <b>Pack Size: &nbsp<%= @product.pack_size %><br>  
			<% if @product.document.file? %>
			  <%= link_to 'Spec Sheet (PDF)', @product.document.url, :target => "_blank" %><br>
			<% end %>
	</p><br>
<% if user_signed_in? %>
      <%= link_to edit_product_path(@product) do %>
        <span class="glyphicon glyphicon-edit"></span>
        Edit
      <% end %> |
<% end %>
<%= link_to 'Back', :back %>

app/views/subcategories/_form.html.erb
<%= form_for(@subcategory) do |f| %>
  <% if @subcategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subcategory.errors.count, "error") %> prohibited this subcategory from being saved:</h2>

      <ul>
      <% @subcategory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  
  <div class="form-group">
  <% options = options_from_collection_for_select(Category.all, 'id', 'description') %>
  <%= f.select :category_id, options, :input_html => { class: "form-control" } %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subcategories/edit.html.erb
<h1>Editing subcategory</h1>

<%= render 'form' %>

<%= link_to 'Show', @subcategory %> |
<%= link_to 'Back', subcategories_path %>

app/views/subcategories/index.html.erb
<h3>Subcategories</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th>Category</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @subcategories.each do |subcategory| %>
      <tr>
        <td><%= subcategory.description %></td>
        <td><%= subcategory.category_id %></td>
        <td><%= link_to 'Edit', edit_subcategory_path(subcategory) %></td>
        <td><%= link_to 'Delete', subcategory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subcategory', new_subcategory_path %>

app/views/subcategories/new.html.erb
<h1>New subcategory</h1>

<%= render 'form' %>

<%= link_to 'Back', subcategories_path %>

app/views/subcategories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @subcategory.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @subcategory.category_id %>
</p>

<%= link_to 'Edit', edit_subcategory_path(@subcategory) %> |
<%= link_to 'Sub-Category List', subcategories_path %>